services:
  local-postgres-music-catalog-db:
    image: postgres:latest
    container_name: local-postgres-music-catalog-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - local-postgres-music-catalog-db--data:/var/lib/postgresql/data

volumes:
  local-postgres-music-catalog-db--data:
    driver: local