services:
  local-postgres-music-catalog-db:
    image: postgres:latest
    container_name: local-postgres-music-catalog-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - local-postgres-music-catalog-db--data:/var/lib/postgresql/data

  music-catalog-api:
    container_name: music-catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - local-postgres-music-catalog-db

volumes:
  local-postgres-music-catalog-db--data:
    driver: local